combined_resource_controller:                                   # The name of the controller that will apear on the controller_manager list

  type: "controllers_tutorials/CombinedResourceController"      # This must match the "class name" parameter on the controller_plugins.xml file
  
  joints:                                                       # Then, all the resources needed for the controller must be listed.
    - arm_flex_joint
    - arm_lift_joint
    - arm_roll_joint
    - wrist_flex_joint
    - wrist_roll_joint

