new_head_controller:                                      # The name of the controller that will apear on the controller_manager list

  type: "controllers_tutorials/NewHeadController"         # This must match the "class name" parameter on the controller_plugins.xml file
  
  joints:                                                  # Then, all the resources needed for the controller must be listed.
    - head_pan_joint
    - head_tilt_joint
